# Fuente
font_family JetBrains Mono Nerd Font
font_size 10.0
bold_font auto
italic_font auto

# Colores (gris oscuro)
foreground #e0e0e0
# Este background es para los demás
#background #252525
# Este background generalmente es para catppuccin
background #24273b
background_opacity 0.9
dynamic_background_opacity yes 

# Desactivar la barra de título
# hide_window_decorations yes

# Opcional: Si quieres forzar el modo sin bordes (dependiendo del gestor de ventanas)
wayland_titlebar_color background
macos_titlebar_color background

# Colores ANSI
color0  #3a3a3a
color1  #ff5f5f
color2  #8fff87
color3  #ffffaf
color4  #87afff
color5  #d787d7
color6  #5fffff
color7  #e4e4e4
color8  #ff875f

# Cursor y ventana
cursor #e0e0e0
cursor_shape block
window_padding_width 5

# Soporte para íconos (Powerline/Nerd Fonts)
symbol_map U+E0A0-U+E0A2,U+E0B0-U+E0B3 JetBrains Mono Nerd Font

