# vim:fileencoding=utf-8:foldmethod=marker
# Font 
font_family IosevkaTerm Nerd Font
font_size 10 
bold_font auto
italic_font auto 

enabled_layouts splits:split_axis=horizontal

#: Horizontal Split
map f5 launch --location=hsplit

#: Vertical Split
map f6 launch --location=vsplit

#: Auto split (responsive split)
map f4 launch --location=split

#: Rotate splitted pane (vertical ↔ horizontal)
map f7 layout_action rotate

# Move between panes 
map ctrl+left   neighboring_window left
map ctrl+right  neighboring_window right
map ctrl+up     neighboring_window up
map ctrl+down   neighboring_window down

# Colors 
# dark grey
foreground #e0e0e0
# OneDarkPro:
background #282c34
# 
# Normal:
# background #252525
# Este background generalmente es para catppuccin
# background #24273b
# background_opacity 0.9
# dynamic_background_opacity yes 
background_blur 1

# disable title bar 
hide_window_decorations no

# Optional: to force borderless windows
wayland_titlebar_color background
macos_titlebar_color background

# ANSI Colors
color0  #3a3a3a
color1  #ff5f5f
color2  #8fff87
color3  #ffffaf
color4  #87afff
color5  #d787d7
color6  #5fffff
color7  #e4e4e4
color8  #ff875f

# Cursor 
cursor_trail 1
cursor #e0e0e0
cursor_shape block
window_padding_width 5

# Support for icons (Powerline/Nerd Fonts)
symbol_map U+E0A0-U+E0A2,U+E0B0-U+E0B3 JetBrains Mono NF
