local M = {
  Text = "󰉿 ",
  Unit = "󰑭 ",
  Value = "󰎠 ",
  Keyword = "󰌋 ",
  Snippet = " ",
  Color = "󰏘 ",
  Reference = "󰈇 ",
  Folder = "󰉋 ",
  File = ' ',
  Module = ' ',
  Namespace = ' ',
  Package = ' ',
  Class = ' ',
  Method = ' ',
  Property = ' ',
  Field = ' ',
  Constructor = ' ',
  Enum = ' ',
  Interface = ' ',
  Function = ' ',
  Variable = ' ',
  Constant = ' ',
  String = ' ',
  Number = ' ',
  Boolean = ' ',
  Array = ' ',
  Object = ' ',
  Key = ' ',
  Null = ' ',
  EnumMember = ' ',
  Struct = ' ',
  Event = ' ',
  Operator = ' ',
  TypeParameter = ' ',
}

return {
  symbols = M
}
